i18n/en.pot
package.json
src/App.tsx
src/modules/Intervention/components/AnalysisChart/components/ChartItemComponent/index.tsx
src/modules/Intervention/components/AnalysisChart/helper/get-chart-categories.ts
src/modules/Intervention/components/AnalysisChart/helper/get-chart-plot-options.helper.tsx
src/modules/Intervention/components/AnalysisChart/helper/get-chart-title-object.helper.tsx
src/modules/Intervention/components/AnalysisChart/helper/get-chart-x-axis-options.helper.tsx
src/modules/Intervention/components/AnalysisChart/index.tsx
src/modules/Intervention/components/AnalysisChart/utils/getChartOptions.ts
src/types/index.d.ts
yarn.lock

- Refactored how chart options are obtained
- Fixed issues with chart
labels
- Fixed issues with chart download

fix(Chart Analysis): Fixes & Improvements

---

src/core/services/user.ts
src/core/state/intervention.ts
src/core/state/user.ts
src/modules/Archives/components/ArchiveErrorBoundary/index.tsx
src/modules/Archives/components/ArchiveListHeader/index.tsx
src/modules/Archives/components/ArchiveMenuCell/index.tsx
src/modules/Archives/components/NoArchivesFound/index.tsx
src/modules/Archives/index.tsx
src/modules/Archives/state/data.ts
src/modules/Intervention/components/Header/components/InterventionHeader/components/ArchiveModal/hooks/archive.ts
src/modules/Intervention/components/Header/components/InterventionHeader/index.tsx
src/modules/Intervention/components/Header/components/InterventionList/components/AddButton/components/CloningSelector/hooks/clone.ts
src/modules/Intervention/index.tsx
src/modules/InterventionConfiguration/index.tsx
src/modules/Router/index.tsx
src/shared/components/errors/InterventionAccessError/index.tsx
src/shared/interfaces/access.ts
src/shared/interfaces/user.ts
src/styles/icons.css

feature(Access): Implementation

---

src/modules/InterventionConfiguration/components/Determinants/components/DeterminantArea/component/ConfirmIndicatorDeleteModal.tsx
src/modules/InterventionConfiguration/components/Determinants/components/DeterminantArea/component/Determinants.tsx
src/modules/InterventionConfiguration/components/Determinants/components/DeterminantArea/index.tsx

- Added a confirm message when a user tries to delete an indicator from
an existing intervention

feat(Intervention Configuration): Implementation

---

src/modules/Intervention/components/Header/components/InterventionList/components/AddButton/components/CloningSelector/hooks/clone.ts

- Updated summary when cloning is succesful to solve access issues after
cloning

fix(Cloning): Fixes

---

src/modules/Archives/state/data.ts
src/modules/Intervention/components/Header/components/InterventionList/components/AddButton/components/CloningSelector/hooks/clone.ts

- Implemented access control for archives. Access is now controlled as
per the intervention configuration within the archive

fix(Archive Access): Fixes

---

src/modules/Intervention/components/AnalysisChart/components/ChartItemComponent/index.tsx
src/modules/Intervention/components/AnalysisChart/components/index.tsx
src/modules/Intervention/components/AnalysisChart/index.tsx

- Modified chart height to cover available space on full page

fix(Analysis Chart Full Page): Improvements

---

src/modules/Intervention/components/AnalysisChart/index.tsx
src/modules/Intervention/components/AnalysisChart/utils/getChartOptions.ts

- Relocated period to header on Chart analysis card

fix(Analysis Chart Card): Improvements

---

src/constants/help/Intervention.tsx
src/modules/Archives/components/ArchiveDashboard/RemarksArea/index.tsx
src/modules/Intervention/components/Header/components/InterventionHeader/components/ArchiveModal/index.tsx

- Renamed archive remarks to archive description
- Added required
indicator to archive description text area field
- Removed unnecessary
helper steps on the archive page

fix(Archive): Fixes & Improvements

---

i18n/en.pot
src/modules/Archives/index.tsx
src/modules/Archives/state/data.ts
src/modules/Intervention/components/Header/components/InterventionHeader/components/ArchiveModal/hooks/archive.ts
src/modules/Intervention/components/Header/components/InterventionHeader/components/ArchiveModal/index.tsx
src/shared/services/archives.ts

- Allowed for multiple archives with the same intervention,period and
organisation unit

feat(Archive): Improvements

---

src/modules/Migration/hooks/useMigrate.ts
src/modules/Migration/hooks/useQueue.ts
src/modules/Migration/index.tsx
src/modules/Migration/services/migrate.ts
src/shared/services/getOldInterventions.ts
yarn.lock

- Fixed issues with migration not importing all interventions
- Fixed
issues with too much rerender

fix(Migration): Fixes & Improvements

---

package.json
src/modules/Intervention/components/AnalysisChart/utils/getChartOptions.ts
src/modules/Intervention/components/Header/components/InterventionList/components/InterventionChips.tsx
src/modules/Intervention/components/Header/components/InterventionList/index.tsx
yarn.lock

- add values on display tooltip
- style tooltip
- refix bottom space on tooltip container
- add opt to display name or short name

              fix(chart-tooltip): on hover

---

cypress.json
package.json
src/modules/Intervention/components/AnalysisChart/utils/getChartOptions.ts

- refactor indexing name on list of indicators name

                 fix(chart-tooltip): on display name of indicator

---

src/modules/InterventionConfiguration/index.tsx

- Fixed validation fail if user clicks on save and exit
- Fixed validation trigger when user clicks on previous
Signed-off-by: Gift Nnko <nnkogift@hotmail.com>

fix(Intervention Config): Fixes

---

cypress/integration/1-Intervention_Configuration.feature
cypress/integration/2-Intervention_List_View.feature
cypress/integration/3-Intervention_View.feature
cypress/integration/4-Intervention_Download.feature
cypress/integration/5-Intervention_Archive.feature
cypress/integration/6-Intervention_Delete.feature

- Created new scenarios for automated testing
Signed-off-by: Gift Nnko <nnkogift@hotmail.com>

test(e2e tests): Scenarios

---

src/modules/Intervention/components/AnalysisChart/utils/getChartOptions.ts

- Wrapped chart labels when they extend the specified width for image & pdf exports

:bug: fix(chart-labels): Fixes

---

src/modules/Archives/components/ArchiveListHeader/index.tsx
src/modules/Intervention/components/Header/components/InterventionHeader/components/MoreMenu.tsx

- Rearranged the more options in the menu item as per suggestion (https://dhis2.atlassian.net/browse/HISP-11)
Fixes jira issue [HISP-11](https://dhis2.atlassian.net/browse/HISP-11)

:bug: fix(intervention more button): Fixes & Improvements

---

.idea/bottleneck-analysis-app.iml
i18n/en.pot
src/App.tsx
src/modules/Intervention/components/AnalysisChart/state/data.ts
src/modules/Intervention/components/SubLevelAnalysis/state/data.ts
src/shared/services/customFunctionAnalytics.ts

- used promise.all instead of map to get custom function data
- included custom function in data items count to check if there are data values configured for the intervention
- Modified the way jQuery is imported to the system
Fixes Issue [HISP-247](https://dhis2.atlassian.net/browse/HISP-247)

:bug: fix(custom functions analytics): Fixes & Improvements

---

i18n/en.pot
src/modules/Intervention/components/AnalysisChart/services/getChartAnalytics.ts
src/modules/Intervention/components/AnalysisChart/state/data.ts
src/modules/Intervention/components/SubLevelAnalysis/state/data.ts
src/shared/services/customFunctionAnalytics.ts

- Fixed issues with interventions with only custom functions crashing
- Modified how custom functions are pulled from datastore
- Refactored get analytics function from chart and sub level components to one area

:bug: fix(custom function analytics): Fixes & Improvements

---

src/modules/InterventionConfiguration/components/Access/component/Access-Add/index.tsx
src/modules/InterventionConfiguration/components/Access/index.tsx
src/modules/InterventionConfiguration/components/Determinants/components/DeterminantArea/component/Determinants.tsx
src/modules/InterventionConfiguration/components/Determinants/components/DeterminantArea/hooks/useItemOperations.ts
src/modules/InterventionConfiguration/components/Determinants/components/DeterminantArea/index.tsx
src/modules/InterventionConfiguration/components/Determinants/components/IndicatorConfiguration/index.tsx
src/modules/InterventionConfiguration/components/Determinants/components/IndicatorSelector/index.tsx
src/modules/InterventionConfiguration/components/Determinants/index.tsx
src/modules/InterventionConfiguration/components/General/components/LegendDefinitionConfigDetails/index.tsx
src/modules/InterventionConfiguration/components/General/components/MapConfiguration/components/ThematicLayer/index.tsx
src/modules/InterventionConfiguration/components/General/index.tsx
src/modules/InterventionConfiguration/constants/steps.tsx
src/modules/InterventionConfiguration/hooks/save.ts
src/modules/InterventionConfiguration/index.tsx
src/modules/InterventionConfiguration/interfaces/index.ts
src/modules/InterventionConfiguration/state/edit.ts

- Utilized only one instance of form for all configuration
- Fixed issues with save and continue misbehaving

:bug: fix(intervention configuration): Save and continue fix

---

src/modules/Migration/services/migrate.ts
src/shared/utils/orgUnit.ts

- Fixed issues with org unit migration for user/level related org units

Organisation unit config migration issues fix

---

package.json
src/modules/Intervention/components/SubLevelAnalysis/components/SubLevelHeader/index.tsx
src/modules/Intervention/components/SubLevelAnalysis/constants/tabs.tsx
src/modules/Intervention/components/SubLevelAnalysis/index.tsx

- refactor current chip/button implimentations
- add tabs into sub level analysis per feedbacks

                 feat:impliment tabs into sub-level analysis

---

src/modules/Intervention/components/AnalysisChart/services/getChartAnalytics.ts
src/modules/Intervention/components/AnalysisChart/state/data.ts
src/modules/Intervention/components/SubLevelAnalysis/state/data.ts
src/modules/Intervention/components/SubLevelAnalysis/state/dimensions.ts

- Fixed issues with sub level fetching all org units of specified level instead of those of the specified org unit

Sub-level data fetch fixes

---

src/modules/Intervention/components/AnalysisChart/index.tsx
src/modules/Intervention/components/Card/index.tsx
src/modules/Intervention/components/CardHeader/index.tsx
src/modules/Intervention/components/RootCauseAnalysis/index.tsx
src/modules/Intervention/components/SubLevelAnalysis/components/SubLevelHeader/index.tsx

- Standardized card headers for all three cards to the format `Intervention name, OrgUnit - Period`
- Header styling improvements

Intervention card headers: Standardizing titles

---

src/constants/defaults.ts

- Changed default public access to `No Access`

Intervention config: Changed default intervention access to `No Access`

---

i18n/en.pot
package.json
src/modules/Intervention/components/SubLevelAnalysis/components/Dictionary/components/SingleDictionary/index.tsx
src/modules/Intervention/components/SubLevelAnalysis/components/Dictionary/state/index.ts
src/modules/Intervention/components/SubLevelAnalysis/components/Dictionary/utils/functions/functionDictionary.ts
src/modules/Intervention/components/SubLevelAnalysis/components/Dictionary/utils/functions/shared.ts
yarn.lock

- Added error page for custom functions in the indicator dictionary
- Added error boundary for the specific indicator

Indicator dictionary fixes & improvements

---

src/modules/Intervention/components/AnalysisChart/utils/getChartOptions.ts

- Set chart font to roboto
- Fixed issues with labels overlapping on downloading

Fixes and improvements on chart download

---

i18n/en.pot
package.json
src/modules/InterventionConfiguration/components/Determinants/components/DeterminantArea/hooks/useItemOperations.ts
src/modules/InterventionConfiguration/components/Determinants/components/DeterminantArea/index.tsx
src/modules/InterventionConfiguration/components/Determinants/components/IndicatorConfiguration/index.tsx
src/modules/InterventionConfiguration/components/Determinants/index.tsx
src/modules/InterventionConfiguration/components/General/index.tsx
src/modules/InterventionConfiguration/constants/steps.tsx
src/modules/InterventionConfiguration/hooks/save.ts
src/modules/InterventionConfiguration/index.tsx
src/modules/InterventionConfiguration/interfaces/index.ts
src/modules/InterventionConfiguration/utils/validators.ts
yarn.lock

- Fixed issues with validation preventing switching pages
- Refactored indicator configuration to use react-hook-form for validation
- Cleanup and formatting

Configuration validation fixes

---

cypress.json
cypress/integration/0.1-Intervention_Indicators-Configuration/Intervention_Indicators-Configuration.js
cypress/integration/0.2-Archive-Intervention.feature
cypress/integration/0.2-Archive-Intervention/Archive-Intervention.js
cypress/integration/0.3-Root-Cause-Widget.feature
cypress/integration/0.3-Root-Cause-Widget/Root-Cause-Widget.js
src/modules/Archives/components/ArchiveDashboard/index.tsx
src/modules/Archives/components/ArchiveMenuCell/index.tsx
src/modules/Archives/index.tsx
src/modules/Intervention/components/Header/components/InterventionHeader/components/ArchiveModal/index.tsx
src/modules/Intervention/components/Header/components/InterventionHeader/components/MoreMenu.tsx
src/modules/Intervention/components/Header/components/InterventionHeader/index.tsx
src/modules/Intervention/components/Header/components/InterventionList/components/AddButton/index.tsx

- Fixing issues with tests which occur due to UI changes

Bugfix: Fixing tests

---

src/modules/Intervention/components/RootCauseAnalysis/services/data.ts

- Fixed issues with wrong namespace for root cause data

:bug: fix(root-cause-save): Fixes

---

README.md

- Added developer documentation in the README

feat(readme): Implementation

---

package.json
yarn.lock

- Fixed issues with period utilities resolutions

fix(package.json): Fixes

---

.prettierignore
.prettierrc
i18n/en.pot
package.json
src/modules/Intervention/components/AnalysisChart/components/ChartItemComponent/index.tsx
src/modules/Intervention/components/AnalysisChart/utils/getChartOptions.ts
src/modules/InterventionConfiguration/components/Determinants/components/DeterminantArea/index.tsx
src/modules/InterventionConfiguration/components/Determinants/index.tsx
src/modules/InterventionConfiguration/components/General/components/InterventionConfigDetails/index.tsx
yarn.lock

- Implemented configuration that allows user to set whether they allow their charts to go over 100%
- Implemented control of limitation of chart to only have a max of 100

Feature: Over 100 values support
